// Package httpserver builds the Gin engine and runs the HTTP server under fx.
package httpserver

import (
	"context"
	"net/http"
	"time"

	_ "github.com/Edu0liver/prototype-healthy-api/docs" // generated swagger docs
	"github.com/Edu0liver/prototype-healthy-api/internal/shared/config"
	"github.com/Edu0liver/prototype-healthy-api/internal/shared/middleware"
	"github.com/Edu0liver/prototype-healthy-api/pkg/metrics"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerfiles "github.com/swaggo/files"
	ginswagger "github.com/swaggo/gin-swagger"
	"go.uber.org/fx"
	"go.uber.org/zap"
)

// NewEngine creates a bare Gin engine (no default middleware).
func NewEngine(cfg *config.Config) *gin.Engine {
	if cfg.IsProduction() {
		gin.SetMode(gin.ReleaseMode)
	}
	e := gin.New()
	e.Use(cors.Default())
	return e
}

// InstallGlobal wires global middleware and the health endpoint. Run as an
// fx.Invoke so it executes after the engine and middleware are constructed.
func InstallGlobal(e *gin.Engine, mw *middleware.Middleware) {
	e.Use(mw.RequestID(), mw.Recovery(), metrics.Middleware())
	e.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})
	e.GET("/metrics", metrics.Handler())
	// Swagger UI at /swagger/index.html (docs generated by `make swag`).
	e.GET("/swagger/*any", ginswagger.WrapHandler(swaggerfiles.Handler))
}

// Run starts the HTTP server and registers graceful shutdown with fx.
func Run(lc fx.Lifecycle, cfg *config.Config, e *gin.Engine, log *zap.Logger) {
	srv := &http.Server{
		Addr:              ":" + cfg.App.Port,
		Handler:           e,
		ReadHeaderTimeout: 10 * time.Second,
	}
	lc.Append(fx.Hook{
		OnStart: func(context.Context) error {
			log.Info("http server listening", zap.String("addr", srv.Addr))
			go func() {
				if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
					log.Fatal("http server error", zap.Error(err))
				}
			}()
			return nil
		},
		OnStop: func(ctx context.Context) error {
			log.Info("http server shutting down")
			return srv.Shutdown(ctx)
		},
	})
}
